spring:
  application:
    name: gaokao-backend
  datasource:
    name: order
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接配置
    url: jdbc:mysql://127.0.0.1:3306/gaokao?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: szw
    password: 123456

server:
  port: 3002

logging:
  level:
    root: info

mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml


llm:
  host: http://127.0.0.1:11434
  path: /api/chat
  model: qwen2:72b
